

# predefined class name
predefined_class_names = {
    'unlabeled': 0,
    'OUT_Road': 1,
    'OUT_Structure': 2,
    'OUT_Tree': 3,
    'OUT_Fence': 4,
    'OUT_Pole': 5,
    'OUT_Sign': 6,
    'Vehicle': 7,
    'OUT_Curbstone': 8,
    'OUT_Pavement': 9,
    'OUT_Undefined Stuff': 10,
    'IN_Hall Way': 11,
    'IN_Open Space': 12,
    'IN_Wall': 13,
    'IN_Pillar': 14,
    'IN_Obstruction': 15,
    'IN_Gate': 16,
    'IN_Elevator': 17,
    'IN_Sign': 18,
    'IN_Fence': 19,
    'IN_Undefined Stuff': 20,
    'OUT_Grass': 21,
    'Human': 22,
    'OUT_Bench': 23,
    'Stroller': 24,
    'OUT_Sculpture': 25,
    'OUT_Traffic Safety Stuff': 26,
    'Undefined Object': 27,
    'OUT_Gate': 28,
    'Two-wheeled Vehicle': 29,
    'Animal': 30,
    'Wheelchair': 31,
    'IN_Bench': 32,
    'IN_Emergency Stuff': 33
}